#!/usr/bin/dh-exec

dockercli/build/docker => /usr/bin/docker
bundles/dynbinary-daemon/dockerd => /usr/bin/dockerd
libnetwork/docker-proxy => /usr/bin/docker-proxy
tini/build/tini-static => /usr/bin/docker-init

dockercli/contrib/completion/zsh/_docker /usr/share/zsh/vendor-completions/
contrib/check-config.sh /usr/share/moby-docker/contrib/
contrib/nuke-graph-directory.sh /usr/share/moby-docker/contrib/
