name: Smoke

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  build:
    strategy:
      matrix:
        dist:
          - unstable
          - bookworm
          - bullseye-backports
      fail-fast: false
    name: ${{ matrix.dist }}
    env:
      dist: ${{ matrix.dist }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout debian-bin
        uses: actions/checkout@v2 # https://github.com/tianon/debian-bin
        with:
          repository: tianon/debian-bin
          ref: 5cbd9464fdc4a128856aacecb047516390edfff3
          path: .debian-bin
      - name: Prepare PATH
        run: |
          {
            echo "$PWD/.debian-bin/generic"
            echo "$PWD/.debian-bin/docker-sbuild"
          } >> "$GITHUB_PATH"
          sudo apt-get update -qq
          sudo apt-get install -yqq --no-install-recommends devscripts # uscan
      - name: Prepare schroot
        run: |
          docker-image-to-sbuild-schroot --pull "$dist.tar" "debian:$dist"
      - name: Prepare sbuild
        run: |
          docker-sbuild --pull .built "$dist.tar" --help > /dev/null
      - name: GitHub Actions + dpkg-buildpackage slowness workaround...
        run: |
          # dpkg-genbuildinfo is very slow on GitHub Actions (likely due to the large number of installed packages); it helps these tests a LOT to skip that for our dpkg-buildpackage invocations
          gen="$(command -v dpkg-genbuildinfo)"
          sudo dpkg-divert --add --rename --divert "$gen.orig" "$gen"
          sudo ln -sfT /bin/true "$gen"
          # (maybe we should run "dsc-from-source" inside a tiny container instead??)
      - name: Prepare dscs
        run: |
          dsc-from-source .dscs */
      - name: sbuild
        run: |
          for dsc in .dscs/*.dsc; do
            dsc="$(readlink -ev "$dsc")"
            dir="$(dirname "$dsc")"
            dsc="$(basename "$dsc")"
            docker-sbuild \
              --mount "type=bind,src=$dir,dst=/dsc,ro" \
              --workdir /dsc \
              .built \
              "$dist.tar" \
              --bd-uninstallable-explainer apt \
              --build-dep-resolver aptitude \
              --resolve-alternatives \
              --verbose \
              "$dsc"
          done
